### ISSUE TITLE
core.sleep() ignores param and sleeps for 10 seconds in response action

### ISSUE THREAD

**Issue by dimovnike** [sflow/haproxy#2]
When using a response action, this function - sleeps for 10 seconds, no matter what param i pass to it. Also it seems that the wait time always equals timeout connect.  The sample config is:

> global
>     daemon
> 	log /dev/log    local6
>     lua-load /etc/haproxy/delay.lua
> 
> defaults
>     mode http
>     timeout connect 10000ms
> 
> frontend fe
>     bind *:80
>     mode http
>     default_backend b_http_hosts
> 
> 
> backend b_http_hosts
>     mode http
>     http-response lua.delay_response
>     server s_web1 server:80 check
> 
> 

and the LUA code:

> function delay_response(txn)
> 	core.msleep(1)
> end
> 
> core.register_action("delay_response", {"tcp-res", "http-res" }, delay_response);
> 

Note that if core.msleep() is commented out - everything works as expected.

I tested version 1.6 (it hangs 30 seconds there), 1.7 - matches timeout connect, and 1.8 - same as 1.7.

Any idea how to overcome this problem?  All i need is to delay the responses based on information from backend header. 

Thanks.

**Comment by dimovnike** [comment]
I commented on a wrong fork. Sorry for this, im closing this bug now. WIll report it on the correct repo.

**Comment by ghost** [comment]
What is the URL to correct repo?

**Comment by dimovnike** [comment]
i don't know, but i reported this on their mailing list and they fixed it right away.

**Comment by ghost** [comment]
Cool. Generally do you not feel it bit inconvenience to have to use mailing lists if there is an option to use GitHub (i know in this case there isn't)? I personally feel it bit of an annoyance when jumping through various distros/compilers and having to subscribe for too many mailing list just to send a bug report. Maybe GitHub has spoiled me.. can't blame.
